# -*- coding: utf-8 -*-
"""Linear Regration

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ovndG3UsqbZAdq9wziXt3KNIvp_wGe3D
"""

# import the library.....
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files
files.upload()

# import the data set
myFile= pd.read_csv('online_price.csv')

myFile

myFile.shape

"""Check is have any null value """

myFile.isnull().sum()

"""Here the profit is output/level/dependent variable. 
now seperate the output and input in different variavle....

x= all column without profit...
"""

x= myFile.drop(['Profit'],axis=1)

x

"""y= profit column"""

y= myFile['Profit']

y

"""**One hot encoding**. To assign the integer number for a string column..."""

city= pd.get_dummies(x['Area'],drop_first= True)
city

"""Now remove the city column"""

x= x.drop('Area',axis=1)

x

# now concat(add) the city with the x
x= pd.concat([x,city],axis=1)

x

"""Now divide the data set into train & test"""

# import the library
from sklearn.model_selection import train_test_split

# traning and testing the data set....
xtrain, xtest, ytrain, ytest= train_test_split(x,y, test_size= 0.25, random_state=0)

# fit the multiple linear regression to the traning set....
from sklearn.linear_model import LinearRegression

regression= LinearRegression()

regression.fit(xtrain,ytrain)

"""Here the testing data of x & y"""

xtest,ytest

"""Predict of x test"""

predict= regression.predict(xtest)

predict

"""**Now calculate the predict score **"""

regression.score(xtest,ytest)*100

"""**R- Squared Value** """

# import library
from sklearn.metrics import r2_score

"""Calculate the score by R- Square value..."""

score= r2_score(ytest,predict)

score*100